DerethForever.Web/Controllers/ResourceController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Configuration;
using System.IO;
using System.Web.Mvc;
using Lifestoned.DataModel.WorldRelease;
using Lifestoned.Lib.ClientLib.Enum;
using Lifestoned.Providers;

namespace DerethForever.Web.Controllers
{
    public class ResourceController : BaseController
    {
        public ActionResult GetFullyLayeredPngIcon(uint weenieClassId)
        {
            byte[] src = new byte[] { };

            if (weenieClassId > 0)
            {
                try
                {
                    var weenie = ContentProviderHost.CurrentProvider.GetWeenie(null, weenieClassId);
                    src = Lifestoned.Lib.ResourceManager.GetFullyLayeredPngIcon(weenie.ItemType, weenie.UnderlayId, weenie.OverlayId, weenie.IconId, weenie.UIEffects);
                }
                catch (Exception ex)
                {
                    return null;
                }
            }

            return File(src, "image/png");
        }

        [HttpGet]
        public ActionResult GetDynamicIcon(int? itemType, uint? underlayId, uint? overlayId, uint? iconId, int? uiEffects)
        {
            byte[] src = new byte[] { };
            src = Lifestoned.Lib.ResourceManager.GetFullyLayeredPngIcon(itemType, underlayId, overlayId, iconId, uiEffects);
            return File(src, "image/png");
        }

        [HttpGet]
        public ActionResult GetImage(uint imageId)
        {
            byte[] src = new byte[] { };

            if (imageId > 0)
            {
                try
                {
                    src = Lifestoned.Lib.ResourceManager.GetPngImage(imageId);
                }
                catch (Exception ex)
                {
                    return null;
                }
            }

            return File(src, "image/png");
        }

        [HttpGet]
        public ActionResult GetCurrentWorldRelease()
        {
            byte[] src = new byte[] { };
            Release info = new Release();

            try
            {
                info = ContentProviderHost.CurrentProvider.GetCurrentWorldReleaseInfo(GetUserToken());
                src = ContentProviderHost.CurrentProvider.GetCurrentWorldRelease(GetUserToken());
            }
            catch (Exception)
            {
                return null;
            }

            return File(src, "application/zip", info.FileName);
        }

        [HttpGet]
        public ActionResult GetWorldRelease(string fileName)
        {
            byte[] src = new byte[] { };

            if (fileName?.Length > 0)
            {
                try
                {
                    src = ContentProviderHost.CurrentProvider.GetWorldRelease(GetUserToken(), fileName);
                }
                catch (Exception)
                {
                    return null;
                }
            }

            return File(src, "application/zip");
        }

        [HttpGet]
        public ActionResult GetCurrentWorldReleaseInfo()
        {
            Release releaseInfo = new Release() { Type = ReleaseType.Unknown };

            try
            {
                releaseInfo = ContentProviderHost.CurrentProvider.GetCurrentWorldReleaseInfo(GetUserToken());
            }
            catch (Exception)
            {
                return null;
            }

            return Json(releaseInfo);
        }

        [HttpGet]
        public ActionResult GetWorldReleaseInfo(string fileName)
        {
            Release src = new Release() { Type = ReleaseType.Unknown };

            if (fileName?.Length > 0)
            {
                try
                {
                    src = ContentProviderHost.CurrentProvider.GetWorldReleaseInfo(GetUserToken(), fileName);
                }
                catch (Exception)
                {
                    return null;
                }
            }

            return Json(src);
        }
    }
}

DerethForever.Web/Controllers/WeenieController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DerethForever.Web.Models.Discord;
using log4net;
using Lifestoned.DataModel.Gdle;
using Newtonsoft.Json;
using RestSharp;
using Lifestoned.DataModel.Shared;
using Lifestoned.DataModel.Account;
using Lifestoned.Providers;

namespace DerethForever.Web.Controllers
{
    public class WeenieController : BaseController
    {
        private const string _Session_IndexModel = "__weenieIndexModel";
        private const string _Session_DownloadModel = "__weenieDownloadModel";

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public IndexModel CurrentIndexModel
        {
            get { return (IndexModel)Session[_Session_IndexModel]; }
            set { Session[_Session_IndexModel] = value; }
        }

        public DownloadChangeModel CurrentDownload
        {
            get { return (DownloadChangeModel)Session[_Session_DownloadModel]; }
            set { Session[_Session_DownloadModel] = value; }
        }

		[HttpGet]
		public ActionResult SpellList()
        {
            return View("SpellListPopup");
        }

        [HttpGet]
        public ActionResult Recent()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            model.Results = SandboxContentProviderHost.CurrentProvider.RecentChanges(GetUserToken());

            return View(model);
        }

        [HttpGet]
        public ActionResult AllUpdates()
        {
            var allUpdates = SandboxContentProviderHost.CurrentProvider.AllUpdates(GetUserToken());
            var zipFile = new ZipFile();
            foreach (var update in allUpdates)
            {
                // build the CachePwn json for this weenie
                var weenie = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), update.WeenieClassId);
                // var cachePwn = Weenie.ConvertFromWeenie(weenie);
                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
                var contents = JsonConvert.SerializeObject(weenie, Formatting.None, settings);

                // build filename
                var name = weenie.Name;
                var removeChars = new List<string>() { "\t", "\n", "!", "\"" };
                foreach (var removeChar in removeChars)
                    name = name.Replace(removeChar, "");

                var filename = $"{update.WeenieClassId} - {name}.json";

                // add json to zip file
                zipFile.AddFile(filename, contents);
            }

            var bytes = zipFile.BuildZip();
            string date = string.Format("{0:yyyy-MM-dd_hh-mm}", DateTime.Now);
            return File(bytes, "application/zip", "GDLE-Latest-Updates-" + date + ".zip");
        }

        [HttpGet]
        public ActionResult Index()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            BaseModel current = CurrentBaseModel;
            BaseModel.CopyBaseData(current, model);
            CurrentBaseModel = current;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(IndexModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                string token = GetUserToken();

                model.Results = SandboxContentProviderHost.CurrentProvider.WeenieSearch(token, model.Criteria);

                if (!string.IsNullOrEmpty(token))
                {
                    List<WeenieChange> mine = SandboxContentProviderHost.CurrentProvider.GetMyWeenieChanges(GetUserToken());
                    model.Results.ForEach(w =>
                    {
                        if (mine.Any(m => m.Weenie.WeenieId == w.WeenieClassId))
                            w.HasSandboxChange = true;
                    });
                }

                model.ShowResults = true;
            }
            catch (Exception ex)
            {
                model.Results = null;
                model.ShowResults = false;
                model.ErrorMessages.Add("Error retrieving data from the SandboxContentProviderHost");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            SortTheThings(model);
            return View(model);
        }

        private void SortTheThings(Weenie model)
        {
            if (model == null)
                return;

            var deprecatedWeenieTypeProperty = model.IntStats.FirstOrDefault(ip => ip.Key == 9007);
            if (deprecatedWeenieTypeProperty != null)
                model.IntStats.Remove(deprecatedWeenieTypeProperty);

            // Setting sort order for edit
            model.IntStats = model.IntStats.OrderBy(ip => ip.Key).ToList();
            model.FloatStats = model.FloatStats.OrderBy(dp => dp.Key).ToList();

            int emoteOrder = 0;

            if (model.EmoteTable != null)
            {
                model.EmoteTable = model.EmoteTable.OrderBy(e => e.EmoteCategoryId).ToList();
                model.EmoteTable.ForEach(
                    t => t.Emotes = t.Emotes?.OrderBy(e => e.SortOrder).Select(ts =>
                        {
                            if (ts.SortOrder != null && ts.SortOrder.Value > emoteOrder)
                                emoteOrder = ts.SortOrder.Value;
                            else
                                ts.SortOrder = ++emoteOrder;

                            int actionOrder = 0;
                            ts.Actions = ts.Actions?.OrderBy(ea => ea.SortOrder).Select(tsa =>
                            {
                                if (tsa.SortOrder != null && tsa.SortOrder.Value > actionOrder)
                                    actionOrder = tsa.SortOrder.Value;
                                else
                                    tsa.SortOrder = ++actionOrder;

                                return tsa;
                            }).ToList();
                            return ts;
                        }).ToList());
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult Clone(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            model = JsonConvert.DeserializeObject<Weenie>(JsonConvert.SerializeObject(model));
            model.WeenieId = 0;
            model.IsCloneMode = true;
            //ImportedWeenie = model;
            return View("New", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Clone(Weenie model)
        {
            ActionResult result = HandlePostback(model);

            if (result != null)
                return result;

            result = ValidateWeenie(model);

            if (result != null)
                return result;

            model.CleanDeletedAndEmptyProperties();
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                SandboxContentProviderHost.CurrentProvider.CreateWeenie(GetUserToken(), model);

                IndexModel indexModel = new IndexModel();
                indexModel.SuccessMessages.Add("Weenie " + model.WeenieId.ToString() + " successfully created.");
                CurrentIndexModel = indexModel;

                return RedirectToAction("Sandbox");
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving weenie in the API");
                model.Exception = ex;
            }

            return View("New", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult New()
        {
            Weenie model = new Weenie();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditImported()
        {
            Weenie model = ImportedWeenie;

            if (model == null)
                RedirectToAction("Upload");

            Weenie existing = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), model.WeenieId);
            if (existing == null)
                return RedirectToAction("NewImported");

            SortTheThings(model);

            return View("Edit", model);
        }

        [HttpGet]
        [Authorize]

DerethForever.Web/Views/Weenie/Delete.cshtml
@using DerethForever.Web.Controllers;
@using Lifestoned.DataModel.Gdle;
@using Lifestoned.DataModel.Shared;
@model Weenie

@{
    ViewBag.Title = "Delete " + Model.Name;
}

<br />

<h4>Confirm deletion of @(Html.Raw(Model.Name)), @(Html.Raw(Model.WeenieClassId))?</h4>

<br />

@Html.DisplayFor(m => m, "InfoMessages")

@using (Html.BeginForm("Delete", "Weenie", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.WeenieId)
    @Html.HiddenFor(m => m.MvcAction)

    <button class="btn btn-danger" id="btnDelete">Delete</button>
    <button class="btn btn-warning" id="btnCancel">Cancel</button>
}

@section scripts {
    <script language="javascript">
        $("#btnDelete").on("click", function () {
            $("#MvcAction").val(@((int)WeenieCommands.Delete));
            $("form").submit();
        });

        $("#btnCancel").on("click", function () {
            $("#MvcAction").val(@((int)WeenieCommands.Cancel));
            $("form").submit();
        });
    </script>
}

DerethForever.Web/Views/Weenie/Edit.cshtml
@using Lifestoned.DataModel.Gdle;
@using Lifestoned.DataModel.Shared
@model Weenie

@{
    ViewBag.Title = "Edit " + Model.Name;
}

<br />

@using (Html.BeginForm("Edit", "Weenie", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="btn-group-vertical stuck" role="group">
        <button id="btnSave" type="submit" class="btn btn-primary" title="Save"><i class="glyphicon glyphicon-floppy-save"></i></button>
        <a href="@Url.Action("Edit", "Weenie", new { id = Model.WeenieClassId })" class="btn btn-primary" title="Cancel"><i class="glyphicon glyphicon-remove"></i></a>
        @if (User.IsInRole("Admin"))
        {
            <a href="@Url.Action("Delete", "Weenie", new { id = Model.WeenieClassId })" class="btn btn-primary" title="Delete"><i class="glyphicon glyphicon-trash"></i></a>
        }
        <a id="preview" target="_blank" href="http://ac.yotesfan.com/10-Clothing/preview.php?id={{cid}}&setup={{sid}}&pal={{pid}}" class="btn btn-primary" title="preview"><i class="glyphicon glyphicon-search"></i></a>
    </div>

    <div class="form-horizontal">
        <h2>
            Edit @Html.Raw(Model.Name) (@(Html.DisplayFor(m => m.WeenieClassId)))
            @if (Model.IconId != null)
            {
                <div class="icon">
                    <img src="@Url.Action("GetFullyLayeredPngIcon", "Resource", new { weenieClassId = Convert.ToUInt32(Model.WeenieClassId) }) " />
                </div>
            }
        </h2>
        <hr />
        <div class="container">

            @Html.HiddenFor(m => m.WeenieClassId)
            @Html.HiddenFor(m => m.MvcAction)
            @Html.HiddenFor(m => m.PropertyTab)
            @Html.DisplayFor(m => m, "InfoMessages")

            <div class="well">
                <div class="row row-spacer">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.IsDone)
                    </div>
                    <div class="col-md-8">
                        @Html.CheckBoxFor(m => m.IsDone)
                    </div>
                </div>
                <div class="row row-spacer">
                    Check this box when this weenie is completely done with editing for purposes of restoring Dereth to its January 2017 state.
                </div>
            </div>

            @Html.EditorFor(m => m)

            <div class="panel panel-default">
                <div class="panel-heading"><h3 class="panel-title">Changelog</h3></div>
                <div class="panel-body">
                    @Html.DisplayFor(m => m.Changelog, "Changelog")

                </div>
            </div>

            <div class="well">
                <div class="row row-spacer">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.ModifiedBy)
                    </div>
                    <div class="col-md-4">
                        @Html.HiddenFor(m => m.ModifiedBy)
                        @Html.DisplayFor(m => m.ModifiedBy)
                    </div>
                </div>

                <div class="row row-spacer">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.LastModified)
                    </div>
                    <div class="col-md-4">
                        @Html.HiddenFor(m => m.LastModified)
                        @Html.DisplayFor(m => m.LastModified)
                    </div>
                </div>

                <div class="row row-spacer">
                    <div class="col-md-2">
                        @Html.Label("Changelog Entry")
                    </div>
                    <div class="col-md-8">
                        @Html.TextAreaFor(m => m.UserChangeSummary, new { @class = "form-control" , rows = "8" })
                    </div>
                </div>
            </div>

        </div>

    </div>

}

@section scripts {
    @Html.Partial("EditorScript")
}

DerethForever.Web/Views/Weenie/LogIntoManagedWorld.cshtml
@using DerethForever.Web.Controllers
@model DerethForever.Web.Models.Weenie.DownloadChangeModel

@{
    ViewBag.Title = "Log in to Managed Server";
}

<h2>Log in to Managed Server</h2>

<br />

@using (Html.BeginForm("LogIntoManagedWorld", "Weenie", FormMethod.Post))
{
    @Html.HiddenFor(m => m.FromUserGuid)
    @Html.HiddenFor(m => m.WeenieId)
    @Html.HiddenFor(m => m.TargetServerGuid)
    @Html.HiddenFor(m => m.PreviewOnly)

    @Html.DisplayFor(m => m, "InfoMessages")

    <div class="well">
        <div class="row row-spacer">
            <div class="col-md-2 col-md-offset-2">
                @Html.Label("Username")
            </div>
            <div class="col-md-3">
                @Html.TextBoxFor(m => m.TargetServerUsername, new { @class = "form-control" })
            </div>
        </div>
        <div class="row row-spacer">
            <div class="col-md-2 col-md-offset-2">
                @Html.Label("Password")
            </div>
            <div class="col-md-3">
                @Html.PasswordFor(m => m.TargetServerPassword, new { @class = "form-control" })
            </div>
        </div>
        <div class="row row-spacer">
            <div class="col-md-2 col-md-offset-4">
                <input type="submit" value="Log In" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

DerethForever.Web/Views/Weenie/New.cshtml
@using Lifestoned.DataModel.Gdle;
@using Lifestoned.DataModel.Shared
@model Weenie

@{
    ViewBag.Title = "Create " + Model.Name;
}

<br />

@using (Html.BeginForm(Model.IsCloneMode ? "Clone" : "New", "Weenie", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="btn-group-vertical stuck" role="group">
    <button id="btnSave" type="submit" class="btn btn-primary" title="Save"><i class="glyphicon glyphicon-floppy-save"></i></button>
    <a href="@Url.Action("Edit", "Weenie", new { id = Model.WeenieClassId })" class="btn btn-primary" title="Cancel"><i class="glyphicon glyphicon-remove"></i></a>
    @if (User.IsInRole("Admin"))
    {
        <a href="@Url.Action("Delete", "Weenie", new { id = Model.WeenieClassId })" class="btn btn-primary" title="Delete"><i class="glyphicon glyphicon-trash"></i></a>
    }
    <a id="preview" target="_blank" href="http://ac.yotesfan.com/10-Clothing/preview.php?id={{cid}}&setup={{sid}}&pal={{pid}}" class="btn btn-primary" title="preview"><i class="glyphicon glyphicon-search"></i></a>
</div>

    <div class="form-horizontal">
        <h2>
            New @Html.Raw(Model.Name) (@(Html.DisplayFor(m => m.WeenieClassId)))
            @if (Model.IconId != null)
            {
                <div class="icon">
                    <!-- GetDynamicIcon(int? itemType, uint? underlayId, uint? overlayId, uint? iconId, int? uiEffects)-->
                    <img src="@Url.Action("GetDynamicIcon", "Resource",
                                  new {
                                      itemType = Model.ItemType,
                                      underlayId = Model.UnderlayId,
                                      overlayId = Model.OverlayId,
                                      iconId = Model.IconId,
                                      uiEffects = Model.UIEffects }) "/>
                </div>
            }
        </h2>
        <hr />
        <div class="container">

            @Html.HiddenFor(m => m.MvcAction)
            @Html.HiddenFor(m => m.PropertyTab)
            @Html.HiddenFor(m => m.IsCloneMode)
            @Html.DisplayFor(m => m, "InfoMessages")

            <div class="well">
                <div class="row row-spacer">
                    <div class="col-md-2">
                        @Html.LabelFor(m => m.IsDone)
                    </div>
                    <div class="col-md-8">
                        @Html.CheckBoxFor(m => m.IsDone)
                    </div>
                </div>
                <div class="row row-spacer">
                    Check this box when this weenie is completely done with editing for purposes of restoring Dereth to its January 2017 state.
                </div>
            </div>

            <div class="well">
                <div class="row row-spacer">
                    <div class="col-md-2 vcenter">
                        @Html.Label("Weenie ID")
                    </div>
                    <div class="col-md-8 vcenter">
                        @Html.TextBoxFor(m => m.WeenieClassId, new { @class = "form-control force-inline" })
                    </div>
                </div>
            </div>

            @Html.EditorFor(m => m)

        </div>

    </div>

}

@section scripts {
@Html.Partial("EditorScript")
}

DerethForever.Web/Views/Weenie/Recent.cshtml
@model Lifestoned.DataModel.Gdle.IndexModel

@{
    ViewBag.Title = "Recent Changes";
}

<br/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <h4>Most Recent Weenie Changes</h4>

    @Html.Partial("WeenieList", Model.Results)

}

DerethForever.Web/Views/Weenie/Sandbox.cshtml
@model Lifestoned.DataModel.Gdle.SandboxModel

@{
    ViewBag.Title = "Review Sandbox Changes";
}

<h2>My Sandbox Changes</h2>

<br/>

@if (Model?.Changes == null || Model.Changes.Count < 1)
{
    <div class="alert alert-info">
        There are no changes to review.
    </div>
}
else
{
    @Html.EditorFor(m => m.Changes, "WeenieChangeList")
}

DerethForever.Web/Views/Weenie/SelectManagedWorld.cshtml
@using DerethForever.Web.Controllers
@model DerethForever.Web.Models.Weenie.DownloadChangeModel

@{
    ViewBag.Title = "Send Weenie to Managed Server";
}

<h2>Send Weenie to Managed Server</h2>

<br/>

@if (Model.TargetServerGuid == null)
{
    using (Html.BeginForm("SelectDfServer", "Weenie", FormMethod.Post))
    {
        @Html.HiddenFor(m => m.FromUserGuid)
        @Html.HiddenFor(m => m.WeenieId)
        @Html.HiddenFor(m => m.PreviewOnly)
        @Html.DropDownListFor(m => m.TargetServerGuid, BaseController.CurrentUser.ManagedWorldSelectListItems, "Select a Server", new { @class = "form-control" })
    }
}
else 
{
    <div class="alert alert-warning">
        You have reached this page in error.  Please file a bug report.
    </div>
}

DerethForever.Web/Views/Weenie/Submissions.cshtml
@model Lifestoned.DataModel.Gdle.SandboxModel

@{
    ViewBag.Title = "Review Sandbox Submissions";
}

<h2>Review Sandbox Submissions</h2>

<br />

@if (Model.Changes == null || Model.Changes.Count < 1)
{
    <div class="alert alert-info">
        There are no changes to review.
    </div>
}
else
{
    @Html.EditorFor(m => m.Changes, "SubmissionList")
}

DerethForever.Web/Views/Weenie/Upload.cshtml
@{
    ViewBag.Title = "Upload GDLE Json";
}

<div class="form-horizontal" >
    <h2>
        Upload JSON File
    </h2>
    <hr />

    <p>
    Using this page you can upload <a href="#" data-toggle="tooltip" title="Intended to import/modify originally generated content from the GDLE emulator, not for use importing or modifying copyright protected content.">GDLE json files</a> of 1 object each.
    After upload, you can download it from the @Html.ActionLink("Sandbox", "Sandbox", "Weenie") page.

    At the current time, the following properties are not yet implemented and will therefore be lost
    upon export.  We recommend you restore this data into the JSON before importing into GDLE.
    @*<ul>
        <li>The Targeting data ("bpsd") of body parts is losing some floating point precision.</li>
        <li>Create List's "try to bond" property is flipping from "0" or "1" to "false" or "true".</li>
    </ul>*@

</p>
    <br/>

    <div class="well">
        @*<input type="file" name="UploadFile" id="txtUploadFile" />
        <br/>
        <input type="button" value="Upload" id="btnUpload" class="btn btn-primary" />*@
        <label><input id="chkDone" type="checkbox" />&nbsp;Mark as Done</label>
        <form id="dz" action="@Url.Action("UploadEx2", "Weenie")" class="dropzone"></form>
    </div>
</div>

@section scripts {
    <script language="javascript">
        Dropzone.options.dz = {

            acceptedFiles: 'application/json',
            addRemoveLinks: true,
            parallelUploads: 5,
            params: function () {
                return {
                    done: $('#chkDone').prop('checked')
                };
            },
            init: function () {
                var $this = this;

                $this.on('addedfile', function () {
                });

                $this.on('success', function (file) {
                    $this.removeFile(file);
                });

                $this.on('queueComplete', function () {
                });
            },
            dictResponseError: "Upload Failed {{statusCode}}"
        };
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}