DerethForever.Web/Models/DF/Ability.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DerethForever.Web.Models.Enums;
using Newtonsoft.Json;

namespace DerethForever.Web.Models.DF
{
    public class Ability
    {
        [JsonProperty("ability")]
        public int AbilityId { get; set; }

        [JsonIgnore]
        public string AbilityIdBinder
        {
            get { return ((AbilityId)AbilityId).GetName(); }
        }

        public AbilityId TypedAbilityId
        {
            get { return (AbilityId)AbilityId; }
        }

        [JsonProperty("baseValue")]
        public uint? Base { get; set; }

        [JsonProperty("ranks")]
        public uint? Ranks { get; set; }

        [JsonProperty("experienceSpent")]
        public uint? ExperienceSpent { get; set; }

        [JsonProperty("startingValue")]
        public uint? UnbuffedValue { get; set; }
    }
}

DerethForever.Web/Models/DF/BookPage.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using Newtonsoft.Json;

namespace DerethForever.Web.Models.DF
{
    public class BookPage
    {
        [JsonIgnore]
        public bool Deleted { get; set; }

        [JsonProperty("page")]
        public uint? Page { get; set; }

        [JsonProperty("authorName")]
        public string AuthorName { get; set; }

        [JsonProperty("authorAccount")]
        public string AuthorAccount { get; set; }

        [JsonProperty("authorId")]
        public uint? AuthorId { get; set; }

        [JsonProperty("ignoreAuthor")]
        public bool IgnoreAuthor { get; set; } = false;

        [JsonProperty("pageText")]
        public string PageText { get; set; }
    }
}

DerethForever.Web/Models/DF/Frame.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using Newtonsoft.Json;

namespace DerethForever.Web.Models.DF
{
    public class Frame
    {
        [JsonProperty("origin")]
        public Origin Origin { get; set; }

        [JsonProperty("angles")]
        public Angles Angles { get; set; }
    }
}

DerethForever.Web/Controllers/ModelViewerController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DerethForever.Web.Controllers
{
    public class ModelViewerController : BaseController
    {
        [HttpGet]
        public ActionResult Index(int modelId)
        {
            return View();
        }
    }
}

DerethForever.Web/Controllers/WeenieController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DerethForever.Web.Models.Discord;
using log4net;
using Lifestoned.DataModel.Gdle;
using Newtonsoft.Json;
using RestSharp;
using Lifestoned.DataModel.Shared;
using Lifestoned.DataModel.Account;
using Lifestoned.Providers;

namespace DerethForever.Web.Controllers
{
    public class WeenieController : BaseController
    {
        private const string _Session_IndexModel = "__weenieIndexModel";
        private const string _Session_DownloadModel = "__weenieDownloadModel";

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public IndexModel CurrentIndexModel
        {
            get { return (IndexModel)Session[_Session_IndexModel]; }
            set { Session[_Session_IndexModel] = value; }
        }

        public DownloadChangeModel CurrentDownload
        {
            get { return (DownloadChangeModel)Session[_Session_DownloadModel]; }
            set { Session[_Session_DownloadModel] = value; }
        }

		[HttpGet]
		public ActionResult SpellList()
        {
            return View("SpellListPopup");
        }

        [HttpGet]
        public ActionResult Recent()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            model.Results = SandboxContentProviderHost.CurrentProvider.RecentChanges(GetUserToken());

            return View(model);
        }

        [HttpGet]
        public ActionResult AllUpdates()
        {
            var allUpdates = SandboxContentProviderHost.CurrentProvider.AllUpdates(GetUserToken());
            var zipFile = new ZipFile();
            foreach (var update in allUpdates)
            {
                // build the CachePwn json for this weenie
                var weenie = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), update.WeenieClassId);
                // var cachePwn = Weenie.ConvertFromWeenie(weenie);
                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
                var contents = JsonConvert.SerializeObject(weenie, Formatting.None, settings);

                // build filename
                var name = weenie.Name;
                var removeChars = new List<string>() { "\t", "\n", "!", "\"" };
                foreach (var removeChar in removeChars)
                    name = name.Replace(removeChar, "");

                var filename = $"{update.WeenieClassId} - {name}.json";

                // add json to zip file
                zipFile.AddFile(filename, contents);
            }

            var bytes = zipFile.BuildZip();
            string date = string.Format("{0:yyyy-MM-dd_hh-mm}", DateTime.Now);
            return File(bytes, "application/zip", "GDLE-Latest-Updates-" + date + ".zip");
        }

        [HttpGet]
        public ActionResult Index()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            BaseModel current = CurrentBaseModel;
            BaseModel.CopyBaseData(current, model);
            CurrentBaseModel = current;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(IndexModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                string token = GetUserToken();

                model.Results = SandboxContentProviderHost.CurrentProvider.WeenieSearch(token, model.Criteria);

                if (!string.IsNullOrEmpty(token))
                {
                    List<WeenieChange> mine = SandboxContentProviderHost.CurrentProvider.GetMyWeenieChanges(GetUserToken());
                    model.Results.ForEach(w =>
                    {
                        if (mine.Any(m => m.Weenie.WeenieId == w.WeenieClassId))
                            w.HasSandboxChange = true;
                    });
                }

                model.ShowResults = true;
            }
            catch (Exception ex)
            {
                model.Results = null;
                model.ShowResults = false;
                model.ErrorMessages.Add("Error retrieving data from the SandboxContentProviderHost");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            SortTheThings(model);
            return View(model);
        }

        private void SortTheThings(Weenie model)
        {
            if (model == null)
                return;

            var deprecatedWeenieTypeProperty = model.IntStats.FirstOrDefault(ip => ip.Key == 9007);
            if (deprecatedWeenieTypeProperty != null)
                model.IntStats.Remove(deprecatedWeenieTypeProperty);

            // Setting sort order for edit
            model.IntStats = model.IntStats.OrderBy(ip => ip.Key).ToList();
            model.FloatStats = model.FloatStats.OrderBy(dp => dp.Key).ToList();

            int emoteOrder = 0;

            if (model.EmoteTable != null)
            {
                model.EmoteTable = model.EmoteTable.OrderBy(e => e.EmoteCategoryId).ToList();
                model.EmoteTable.ForEach(
                    t => t.Emotes = t.Emotes?.OrderBy(e => e.SortOrder).Select(ts =>
                        {
                            if (ts.SortOrder != null && ts.SortOrder.Value > emoteOrder)
                                emoteOrder = ts.SortOrder.Value;
                            else
                                ts.SortOrder = ++emoteOrder;

                            int actionOrder = 0;
                            ts.Actions = ts.Actions?.OrderBy(ea => ea.SortOrder).Select(tsa =>
                            {
                                if (tsa.SortOrder != null && tsa.SortOrder.Value > actionOrder)
                                    actionOrder = tsa.SortOrder.Value;
                                else
                                    tsa.SortOrder = ++actionOrder;

                                return tsa;
                            }).ToList();
                            return ts;
                        }).ToList());
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult Clone(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            model = JsonConvert.DeserializeObject<Weenie>(JsonConvert.SerializeObject(model));
            model.WeenieId = 0;
            model.IsCloneMode = true;
            //ImportedWeenie = model;
            return View("New", model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Clone(Weenie model)
        {
            ActionResult result = HandlePostback(model);

            if (result != null)
                return result;

            result = ValidateWeenie(model);

            if (result != null)
                return result;

            model.CleanDeletedAndEmptyProperties();
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                SandboxContentProviderHost.CurrentProvider.CreateWeenie(GetUserToken(), model);

                IndexModel indexModel = new IndexModel();
                indexModel.SuccessMessages.Add("Weenie " + model.WeenieId.ToString() + " successfully created.");
                CurrentIndexModel = indexModel;

                return RedirectToAction("Sandbox");
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving weenie in the API");
                model.Exception = ex;
            }

            return View("New", model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult New()
        {
            Weenie model = new Weenie();

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditImported()
        {
            Weenie model = ImportedWeenie;

            if (model == null)
                RedirectToAction("Upload");

            Weenie existing = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), model.WeenieId);
            if (existing == null)
                return RedirectToAction("NewImported");

            SortTheThings(model);

            return View("Edit", model);
        }

        [HttpGet]
        [Authorize]

DerethForever.Web/Views/Shared/EditorTemplates/BoolPropertyList.cshtml
@using Lifestoned.DataModel.Gdle;
@model List<BoolStat>

<input type="hidden" id="BoolPropertyCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="col-md-3">
            @Html.DisplayFor(m => m[i].PropertyIdBinder)
            @Html.HiddenFor(m => m[i].Key)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="col-md-2">
            @Html.CheckBoxFor(m => m[i].BoolValue, new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeProperty" value="Remove" />
        </div>
        <div class="col-md-6">
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@Html.CheckBox("", Model.GetValueOrDefault())

DerethForever.Web/Views/Shared/EditorTemplates/CreateList.cshtml
@using Lifestoned.DataModel.Gdle;
@model List<CreateItem>

<div class="panel-heading"><h3 class="panel-title">Create List</h3></div>
<div class="panel-body panel-group">

    @if (Model != null && Model.Count > 0)
    {
        <div class="row row-spacer">
            <div class="col-md-3">@(Html.Label("Weenie"))</div>
            <div class="col-md-3">@(Html.Label("Destination"))</div>
            <div class="col-md-1">@(Html.Label("Palette"))</div>
            <div class="col-md-2">@(Html.Label("Shade"))</div>
            <div class="col-md-1">@(Html.Label("Quantity"))</div>
            <div class="col-md-1">@(Html.Label("Bonded"))</div>
            <div class="col-md-1"></div>
        </div>

        for (int i = 0; i < Model.Count(); i++)
        {
            <div class="row row-spacer">
                <div class="col-md-3">
                    @Html.HiddenFor(m => m[i].Deleted)
                    @Html.TextBoxFor(m => m[i].WeenieClassId, new { @class = "form-control weenieClassEntry weenie-select" })
                </div>
                <div class="col-md-3">
                    @Html.EnumDropDownListFor(m => m[i].Destination_Binder, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    @Html.TextBoxFor(m => m[i].Palette, new { @class = "form-control" })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(m => m[i].Shade, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    @Html.TextBoxFor(m => m[i].StackSize, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    @Html.CheckBoxFor(m => m[i].TryToBond_BooleanBinder, new { @class = "form-control" })
                </div>
                <div class="col-md-1">
                    <input type="button" class="btn btn-xs btn-danger" name="removeCreateItem" value="Remove" />
                </div>
            </div>
        }
    }

</div>

DerethForever.Web/Views/Shared/EditorTemplates/DataIdPropertyList.cshtml
@using Lifestoned.DataModel.Gdle;
@model List<DidStat>

<input type="hidden" id="DidPropertyCount" value="@Model.Count()" />
@for (int i = 0; i < Model.Count(); i++)
{
    <div class="row row-spacer">
        <div class="vcenter col-md-3">
            @Html.DisplayFor(m => m[i].PropertyIdBinder)
            @Html.HiddenFor(m => m[i].Key)
            @Html.HiddenFor(m => m[i].Deleted)
        </div>
        <div class="vcenter col-md-3">
            @Html.TextBoxFor(m => m[i].Value, new { @class = "form-control" })
        </div>
        <div class="vcenter col-md-1">
            <input type="button" class="btn btn-xs btn-danger" name="removeProperty" value="Remove" />
        </div>
        <div class="vcenter col-md-4">
            @if (Model[i].Key == 1)
            {
                // this is the Setup property, and we can give a link to the model viewer here
                // Html.ActionLink("Model Viewer", "Index", "ModelViewer");
            }
        </div>
    </div>
}

DerethForever.Web/Views/Shared/EditorTemplates/EmoteTable.cshtml
@using Lifestoned.DataModel.Shared
@using Lifestoned.DataModel.Gdle
@model List<EmoteCategoryListing>


<div class="panel-heading"><h3 class="panel-title">Emote Table</h3></div>
<div class="panel-body panel-group">

    @for (int k = 0; k < (Model?.Count ?? 0); k++)
    {
        var categoryListing = Model[k];
        var category = (EmoteCategory)categoryListing.EmoteCategoryId;


        <div class="panel panel-default">
            <div class="panel-heading">
                <a data-toggle="collapse" href="#@(Html.Raw("emoteCategory_" + k))">@Html.Label("Emotes for Category: " + category.GetName())</a>
                @Html.HiddenFor(m => m[k].EmoteCategoryId)
            </div>

            <div id="@(Html.Raw("emoteCategory_" + k))" class="panel-collapse collapse">

                @for (int i = 0; i < categoryListing?.Emotes?.Count; i++)
                {
                    <div class="panel-default panel-body">
                        <div class="row-spacer clearfix">
                            @Html.HiddenFor(m => m[k].Emotes[i].Category)
                            @Html.HiddenFor(m => m[k].Emotes[i].Deleted)
                            <div class="col-md-3">
                                @Html.LabelFor(m => m[k].Emotes[i].Probability)
                            </div>
                            <div class="col-md-3">
                                @Html.TextBoxFor(m => m[k].Emotes[i].Probability, new { @class = "form-control" })
                            </div>
                            <div class="col-md-3">

                            </div>
                            <div class="col-md-3">
                                <input type="button" class="btn btn-xs btn-danger" name="removeEmoteSet" value="Remove Emote" />
                            </div>
                        </div>

                        @if (Emote.IsPropertyVisible("Style", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].Style)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].Style, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("Quest", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].Quest)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].Quest, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("SubStyle", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].SubStyle)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].SubStyle, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("ClassId", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].ClassId)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].ClassId, new { @class = "form-control weenieClassEntry weenie-select" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("MaxHealth", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].MaxHealth)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].MaxHealth, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("MinHealth", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].MinHealth)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].MinHealth, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        @if (Emote.IsPropertyVisible("VendorType", Model[k].Emotes[i]))
                        {
                            <div class="row row-spacer">
                                <div class="col-md-3">
                                    @Html.LabelFor(m => m[k].Emotes[i].VendorType)
                                </div>
                                <div class="col-md-3">
                                    @Html.TextBoxFor(m => m[k].Emotes[i].VendorType, new { @class = "form-control" })
                                </div>
                            </div>
                        }

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <a data-toggle="collapse" href="#@(Html.Raw("emoteCategory_" + k + "_" + i))">@Html.Label("Emotes")</a>
                            </div>
                            <div id="@(Html.Raw("emoteCategory_" + k + "_" + i))" class="panel-collapse collapse">
                                <div class="panel-body panel-group">
                                    @Html.EditorFor(m => m[k].Emotes[i].Actions, "EmoteActionList")

                                    @*<div class="row row-spacer">
                                        <div class="col-md-3">
                                            @Html.Label("Add new Emote")
                                        </div>
                                        <div class="col-md-3">
                                            @Html.EnumDropDownListFor(m => m[k].NewEmoteType, new { @class = "form-control" })
                                        </div>
                                        <div class="col-md-3">
                                            <input type="button" class="btn btn-primary" id="addEmote" name="addEmote" value="Add" formaction="Edit" data-content="@(i)" data-container="@(category)" formnovalidate="formnovalidate" />
                                        </div>
                                    </div>*@
                                </div>

                                @EditorHelpers.FooterCommand(
                                    $"addEmote_{k}_{i}",
                                    new { data_content = i, data_container = categoryListing.EmoteCategoryId },
                                    "Add New Emote",
                                    Html.EnumDropDownListFor(m => m[k].Emotes[i].NewEmoteType, new { @class = "form-control" })
                                )
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    }
</div>

DerethForever.Web/Views/Shared/EditorTemplates/Frame.cshtml
@model Lifestoned.DataModel.Gdle.Frame

@Html.TextBoxFor(m => m.Display)

@*<div class="row row-spacer">
    <div class="col-md-2">@Html.Label("Position")</div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">X</span>
            @Html.TextBoxFor(m => m.Position.X, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">Y</span>
            @Html.TextBoxFor(m => m.Position.Y, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">Z</span>
            @Html.TextBoxFor(m => m.Position.Z, new { @class = "form-control" })
        </div>
    </div>
</div>
<div class="row row-spacer quat">
    <div class="col-md-2">@Html.Label("Rotation")</div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">W</span>
            @Html.TextBoxFor(m => m.Rotations.W, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">X</span>
            @Html.TextBoxFor(m => m.Rotations.X, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">Y</span>
            @Html.TextBoxFor(m => m.Rotations.Y, new { @class = "form-control" })
        </div>
    </div>
    <div class="col-md-2">
        <div class="input-group">
            <span class="input-group-addon">Z</span>
            @Html.TextBoxFor(m => m.Rotations.Z, new { @class = "form-control" })
        </div>
    </div>
</div>*@